/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaForm: typeof import('./src/components/Area/AreaForm.vue')['default']
    AreaList: typeof import('./src/components/Area/AreaList.vue')['default']
    DetallePublicidad: typeof import('./src/components/DetallePublicidad/DetallePublicidad.vue')['default']
    DetalleSolicitud: typeof import('./src/components/Solicitud/DetalleSolicitud.vue')['default']
    EstatusForm: typeof import('./src/components/Estatus/EstatusForm.vue')['default']
    Loader: typeof import('./src/components/Loader/Loader.vue')['default']
    MenuForm: typeof import('./src/components/Menu/MenuForm.vue')['default']
    PublicidadForm: typeof import('./src/components/Publicidad/PublicidadForm.vue')['default']
    RolesForm: typeof import('./src/components/Roles/RolesForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolicitudesHistoricoForm: typeof import('./src/components/SolicitudesHistorico/SolicitudesHistoricoForm.vue')['default']
    SolicitudesHistoricoList: typeof import('./src/components/SolicitudesHistorico/SolicitudesHistoricoList.vue')['default']
    TipoPublicidadForm: typeof import('./src/components/TipoPublicidad/TipoPublicidadForm.vue')['default']
    UsuarioRolList: typeof import('./src/components/UsuarioRol/UsuarioRolList.vue')['default']
    UsuariosForm: typeof import('./src/components/Usuarios/UsuariosForm.vue')['default']
  }
}
